version: '3.8'

services:
  node-express:
    image: rogerkondrat/tweeter
    container_name: tweeter
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes:
      - .:/src/app
      - /src/app/node_modules